USE Examination_System 
GO 

CREATE TABLE [User]
(
    UserID INT IDENTITY PRIMARY KEY,
    FName NVARCHAR(20) NOT NULL,    
    LName NVARCHAR(20) NOT NULL,
    BDate DATE NULL,
    Email NVARCHAR(50) NOT NULL,
    Address NVARCHAR(30) NOT NULL,
    Age AS (Year(GETDATE()) - Year(BDATE)),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Password NVARCHAR(256) NOT NULL,
    Role CHAR(1) NOT NULL,
    Gender CHAR(1) NOT NULL ,
    CONSTRAINT CT_GENDER CHECK (GENDER IN ('F' , 'M')),
    CONSTRAINT CT_ROLE CHECK (ROLE IN ('I' , 'A' , 'S')),
) ON 'PRIMARY';
GO

CREATE TABLE Admin
(
    AdminID INT IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    CONSTRAINT FK_Admin_User FOREIGN KEY (UserID)
        REFERENCES [User](UserID)
) ON 'PRIMARY';
GO

CREATE TABLE Instructor
(
    InstructorID INT IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    Degree NVARCHAR(10) NOT NULL ,
    Salary INT NOT NULL,
    HireDate DATE NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Instructor_User FOREIGN KEY (UserID)
        REFERENCES [User](UserID),
    CONSTRAINT CT_DEGREE CHECK (Degree IN ('MS' , 'PHD')),
) ON 'PRIMARY';
GO

CREATE TABLE Student
(
    StudentID INT IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    Faculty NVARCHAR(30) NOT NULL,
    GPA FLOAT NOT NULL,
    GraduationYear INT NOT NULL,
    CONSTRAINT FK_Student_User FOREIGN KEY (UserID)
        REFERENCES [User](UserID),
    CONSTRAINT CT_GPA CHECK (GPA BETWEEN 0.00 and 5.00),

) ON 'PRIMARY';
GO